<?php

namespace App\Http\Controllers;

use App\Models\DeTai;
use Illuminate\Http\Request;
use App\Models\SinhVien;

class DeTaiController extends Controller
{
    // Liệt kê tất cả đề tài
    public function index()
    {
        return DeTai::with('giangVien')->get()->map(function($d) {
            return [
                'MaDT'     => $d->MaDT,
                'TenDeTai' => $d->TenDeTai,
                'MaGV'     => $d->MaGV,
                'GiangVien'=> $d->MaGV ? $d->giangVien->Ho_va_Ten : '',
                'SoLuong'  => $d->SoLuong,
                'TrangThai'=> $d->TrangThai,
            ];
        });
    }

    // Hiển thị thông tin một đề tài
    public function show(DeTai $detai)
    {
        return $detai->load('giangVien');
    }

    // Tạo mới đề tài
    public function store(Request $request)
    {
        $validated = $request->validate([
            'MaDT'    => 'required|string|unique:DeTai,MaDT',
            'TenDeTai'    => 'required|string|max:255',
            'MaGV'     => 'nullable|string|exists:GiangVien,MaGV',
        ]);
        return DeTai::create($validated);
    }

    private function generateMaDT()
    {
        do {
            $number = str_pad(rand(1, 100), 2, '0', STR_PAD_LEFT); // makes 01, 02, 099, 1234
            $maDT = 'DT' . $number;
        } while (DeTai::where('MaDT', $maDT)->exists());

        return $maDT;
    }

    public function saveTopic(Request $request)
    {
        $request->validate([
            'TenDT' => 'required|string',
            'MoTa' => 'nullable|string',
            'TrangThai' => 'required|string',
            'MaGV' => 'required|string'
        ]);

        // Check if topic exists
        $topic = DeTai::where('TenDeTai', $request->TenDT)->first();

        if ($topic) {
            // UPDATE existing topic
            $topic->MoTa = $request->MoTa;
            $topic->TrangThai = $request->TrangThai;
            $topic->MaGV = $request->MaGV;
            $topic->save();

            return response()->json([
                'message' => 'Cập nhật đề tài thành công',
                'data' => $topic
            ]);
        }

        // CREATE new topic (MaDT auto-generated by DB)
        $newTopic = DeTai::create([
            'MaDT' => $this->generateMaDT(),
            'TenDeTai' => $request->TenDT,
            'MoTa' => $request->MoTa,
            'TrangThai' => $request->TrangThai,
            'MaGV' => $request->MaGV
        ]);

        return response()->json([
            'message' => 'Tạo đề tài mới thành công',
            'data' => $newTopic
        ]);
    }
    public function assignTopicToStudent(Request $request)
    {
        $request->validate([
            'MSSV' => 'required|string|exists:SinhVien,MSSV',
            'MaDT' => 'required|string|exists:DeTai,MaDT',
        ]);

        $student = SinhVien::where('MSSV', $request->MSSV)->first();

        if (!$student) {
            return response()->json(['error' => 'Sinh viên không tồn tại'], 404);
        }

        $student->MaDT = $request->MaDT;
        $student->save();

        return response()->json([
            'message' => 'Cập nhật đề tài cho sinh viên thành công',
            'data' => $student
        ]);
    }

    // Cập nhật thông tin đề tài
   public function update(Request $request, $MaDT)
    {
            $detai = DeTai::where('MaDT', $MaDT)->firstOrFail();
        {
            $validated = $request->validate([
                'TenDeTai' => 'required|string|max:255',
                'MaGV'     => 'nullable|string|exists:GiangVien,MaGV',
            ]);

            $detai->update($validated);

            return $detai->load('giangVien');
        }
    }

    // Xóa một đề tài
     public function destroy(Request $request)
    {
        $detai = DeTai::where('MaDT', $request->MaDT)->firstOrFail();
        return $detai->delete();
    }
}
